/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js and must not be edited manually.
// See https://nextjs.org/docs/app/api-reference/config/typescript.
