#!/usr/bin/env bash
# Provider-free installed-release operator gate; never passes host paths in-container.
set -euo pipefail
d=$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd -P); source "$d/lib/dotenv.sh"
mode=plan commit= env= release=/opt/lagrange/current raw= artifact= universe= entitlement= registry= output= batch= capture=
confirm=I_CONFIRM_PROVIDER_FREE_RAW_MATERIALIZATION
die(){ echo "kis-stock-price-beta-materialize: $*" >&2; exit 1; }; blocked(){ echo "BLOCKED_EXTERNAL: $*" >&2; exit 2; }
while [ "$#" -gt 0 ]; do case "$1" in --plan|--preflight|--check|--materialize|--proposal) [ "$mode" = plan ] || die 'one mode'; mode=${1#--};; --commit|--env-file|--release-root|--raw-root|--artifact-root|--universe|--entitlement|--registry|--output|--batch-id|--capture-commit) k=${1#--}; shift; [ "$#" -gt 0 ]||die 'missing value'; case "$k" in commit)commit=$1;;env-file)env=$1;;release-root)release=$1;;raw-root)raw=$1;;artifact-root)artifact=$1;;universe)universe=$1;;entitlement)entitlement=$1;;registry)registry=$1;;output)output=$1;;batch-id)batch=$1;;capture-commit)capture=$1;;esac;; -h|--help) echo 'provider-free materialize wrapper'; exit 0;; *)die "unknown $1";; esac; shift; done
if [ "$mode" = plan ]; then echo 'STOCK_PRICE_BETA_MATERIALIZE_PLAN local=yes docker=no env=no mutation=no'; exit 0; fi
[ "$(id -u)" = 0 ] || die 'root only'; [[ "$commit" =~ ^[0-9a-f]{40}$ && "$capture" =~ ^[0-9a-f]{40}$ ]] || die 'commit'; [[ "$batch" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] || die 'batch UUID'
safe600(){ [ -f "$1" ] && [ ! -L "$1" ] && [ "$(stat -c '%u:%g:%a' "$1")" = 0:0:600 ]; }; [[ "$env" = /* ]] && safe600 "$env" || die 'env root:root 0600 absolute'
release=$(readlink -f "$release")||die 'release'; [[ "$release" =~ /releases/[0-9a-f]{40}$ ]] && [ "${release##*/}" = "$commit" ] && [ "$(stat -c %u "$release")" = 0 ] || die 'release identity'
compose_file=$release/deploy/compose/compose.yml; [ -f "$compose_file" ] && [ ! -L "$compose_file" ] && [ "$(stat -c %u "$compose_file")" = 0 ] || die 'Compose file'
dotenv_load "$env"||die 'env'; dotenv_validate_shell_overrides||die 'env override'; [ "$(dotenv_effective_get LAGRANGE_CODE_COMMIT)" = "$commit" ]||die 'env commit'; data=$(dotenv_effective_get LAGRANGE_DATA_DIR); [[ "$data" = /* ]]||die 'data root'
ue=$release/configs/universes/kr-stock-price-beta-v1.json; ee=$release/configs/data-rights/kis.entitlement.json; re=$release/configs/evidence/kr-stock-price-beta-v1-approved-artifacts.json
[ "$raw" = "$data/raw" ] && [ "$artifact" = "$data/stock-price-beta-artifacts" ] && [ "$universe" = "$ue" ] && [ "$entitlement" = "$ee" ] || die 'host paths must equal reviewed mounts'
for p in "$ue" "$ee" "$re"; do [ -f "$p" ] && [ ! -L "$p" ] && [ "$(stat -c %u "$p")" = 0 ] || die 'installed config unsafe'; done
compose_range_raw_batch_id=$(dotenv_effective_get RANGE_RAW_BATCH_ID); [ -n "$compose_range_raw_batch_id" ] || compose_range_raw_batch_id=compose-config-disabled
compose(){ LAGRANGE_CODE_COMMIT="$commit" RANGE_RAW_BATCH_ID="$compose_range_raw_batch_id" docker compose --profile stock-price-beta-materialize --env-file "$env" --file "$compose_file" "$@"; }
if [ "$mode" = preflight ]; then compose config --quiet||die 'compose'; echo "STOCK_PRICE_BETA_MATERIALIZE_PREFLIGHT commit=$commit data_root=/data raw_mount=/data/raw artifact=/data/artifacts network=none"; exit 0; fi
command -v docker >/dev/null||blocked 'docker'; docker compose version >/dev/null||blocked 'compose'; compose config --quiet||die 'compose'; compose build --pull=false research-stock-price-beta-materialize||die 'build'
image=lagrange-station-research-stock-price-beta-materialize:$commit; [ "$(docker image inspect --format '{{index .Config.Labels "org.opencontainers.image.revision"}}' "$image")" = "$commit" ]||die 'image revision'; image_commit=$(docker image inspect --format '{{range .Config.Env}}{{println .}}{{end}}' "$image"|awk -F= '$1=="LAGRANGE_CODE_COMMIT"{print substr($0,index($0,"=")+1);exit}'); [ "$image_commit" = "$commit" ]||die 'image commit'
args=("$mode" --raw-root /data --artifact-root /data/artifacts --universe /opt/lagrange/configs/universes/kr-stock-price-beta-v1.json --entitlement /opt/lagrange/configs/data-rights/kis.entitlement.json --batch-id "$batch" --capture-commit "$capture")
owner_dir(){ install -d -m 0700 "$1" || die 'directory'; chown 10001:10001 "$1" || die 'directory owner'; chmod 0700 "$1" || die 'directory mode'; [ "$(stat -c '%u:%g:%a' "$1")" = 10001:10001:700 ] || die 'directory metadata'; }
case "$mode" in materialize) [ "${STOCK_PRICE_BETA_MATERIALIZE_CONFIRM:-}" = "$confirm" ]||blocked 'confirmation'; owner_dir "$artifact"; args+=(--confirm "$confirm");; check) [ "$registry" = "$re" ]||die 'registry'; args+=(--registry /opt/lagrange/configs/evidence/kr-stock-price-beta-v1-approved-artifacts.json);; proposal) [ "${STOCK_PRICE_BETA_MATERIALIZE_CONFIRM:-}" = "$confirm" ]||blocked 'confirmation'; [[ "$output" = /* ]] && [ ! -e "$output" ]||die 'proposal'; outdir=$(dirname "$output"); owner_dir "$outdir"; args+=(--output "/data/proposals/${output##*/}" --confirm "$confirm"); compose run --rm --no-deps --volume "$outdir:/data/proposals:rw" research-stock-price-beta-materialize "${args[@]}"; exit $?;; *)die 'mode';; esac
compose run --rm --no-deps research-stock-price-beta-materialize "${args[@]}"
